Project: #test

Method: patho_dbit #dbit/atac/co_atac/co_rna/patho_dbit/patho_atac

Sequence_file:
  file1:  /mnt/d/prog/RNA2_1209_Illu_1.fq.gz
    
  file2: /mnt/d/prog/RNA2_1209_Illu_2.fq.gz

Reference:
  index_file: /home/sanshou/project/toolkit/toolkit/index/GRCm38.primary_assembly.genome.index
  fa_file: /home/sanshou/project/toolkit/toolkit/index/GRCm38.primary_assembly.genome.fa
  gtf_file: /home/sanshou/project/toolkit/toolkit/index/gtf/GRCm38.primary_assembly.gtf

Barcode:
  file: /home/sanshou/project/toolkit/toolkit/barcode/20240614_2500barcode_AB_update.txt

Out_dir:
  dir: /mnt/d/prog/output

Threads: 8

Advanced:
  linker1:
  linker2:
  skipr: #1/2
  UMI: #0/10
  primer: #22
  hdist: #3
  rna_lib: #pcr/illumina
  primer5: #AAGCAGTGGTATCAACGCAGAGTGAATGGG
